### Add new album
POST http://localhost:8085/songs/albums
content-type: application/json

{
    "title": "Sarah Vaughan and Clifford Brown",
    "artist": "Sarah Vaughan"
}
###
GET http://localhost:8085/songs/albums/Sarah%20Vaughan
###
GET http://localhost:8085/songs/albums/falsename